# logging
logging:
  level: INFO
  loggers:
    cz.studenthub: DEBUG
    org.pac4j: DEBUG

# server
server:
  rootPath: /api/

# database - development conf. (not for prod. usage)
database:
  # the name of your JDBC driver
  driverClass: org.postgresql.Driver

  # the username
  user: ${SH_DB_USERNAME:-postgres}

  # the password
  password: ${SH_DB_PASSWORD}

  # the JDBC URL
  url: ${SH_DB_URL:-jdbc:postgresql://localhost:5432/postgres}

  # the SQL query to run when validating a connection's liveness
  validationQuery: "SELECT 1"
  
  # validate schema
  properties:
    hibernate.hbm2ddl.auto: validate
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect